### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/HotKeyManager#1]
This is a library, so don't extend JavaPlugin. Create an init function or something with `Plugin` as the parameter and register events there.

```java
public void init(org.bukkit.plugin.Plugin plugin) {
    plugin.getServer().getPluginManager().registerEvents(this, plugin);
}
```

**Comment by DefinitlyEvil** [comment]
nah, I think it should register itself automatically and other plugins can call it directly. Check out MineLegends.

**Comment by TheDiamondYT1** [comment]
Dont call it a library then... Call it a plugin with an API 😂

**Comment by DefinitlyEvil** [comment]
Yeah, basically it is a plugin with API. xD
